#!/bin/bash
# Get the URL to share with others

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                                                            ║"
echo "║              IA EXTRACTOR - SHARE THIS URL                 ║"
echo "║                                                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Get IP address
IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null)

if [ -z "$IP" ]; then
    echo "❌ Not connected to network"
    echo ""
    echo "Please connect to WiFi and try again."
    exit 1
fi

echo "✅ Your computer's IP address: $IP"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 SHARE THIS URL:"
echo ""
echo "    http://$IP:5001"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Anyone on your WiFi network can:"
echo "  1. Open their browser"
echo "  2. Go to: http://$IP:5001"
echo "  3. Upload PDFs and download Excel files"
echo ""
echo "This works on:"
echo "  ✓ Laptops"
echo "  ✓ Desktop computers"
echo "  ✓ Phones"
echo "  ✓ Tablets"
echo ""
echo "⚠️  Note: Both devices must be on the same WiFi network"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📧 Email this to your assistant:"
echo ""
echo "Subject: IA Data Extractor - Access Link"
echo ""
echo "Hi,"
echo ""
echo "You can now convert IA PDFs to Excel files using this link:"
echo "http://$IP:5001"
echo ""
echo "Just drag and drop your PDF files onto the page!"
echo ""
echo "Make sure you're connected to the office WiFi."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🌐 Want internet access from anywhere?"
echo "   Run: cat ~/ia_extractor_web/INTERNET_ACCESS.md"
echo ""
